### PR TITLE
Fix obtaining network interfaces on MacOSX

### PR DESCRIPTION
**Pull request by mincequi**
Another OSX fix.

### CODE REVIEW

**Comment by RalfOGit** [comment]
Hi Mincequi, I had a look at your changes. Can you elaborate a bit more on these. The code looks a bit uglier this way. Is there a reason to revert to pointer arithmetics for MacOSX? Best regards

**Comment by mincequi** [comment]
Yes, this looks a little uglier. However, on OSX the length of the interfaces are dynamic and have to be respected.
Please have a look at: https://gist.github.com/OrangeTide/909204

Unfortunately, there is no other way, to make it run on OSX.

**Comment by RalfOGit** [comment]
OK, I see.

**Comment by RalfOGit** [comment]
It is merged now. Thanks for the MacOSX changes. 
Today I was working on forwarding the emeter multicast packets to a different subnet. For this to work cleanly, I will need add code to query the subnet masks for each of the local interfaces. This is in the same area that you were doing changes. Are you done with your MacOSX changes in this method?

**Comment by mincequi** [comment]
Ok, thanks for merging. Since this is working for me, i do not plan any other changes.

However, once could optimize a little bit within the LocalHost class.
Generally, doing complex work in constructor is not recommended. One could move the cacheXXXX() calls  within the constructor to their corresponding getters to do this caching lazily.
This is just a recommendation. I do not plan to do that soon.

**Pull request merged**
